feat: New error: Failed downloading rpms for hermetic builds due to 504 errors
Error from collected-data/jhutar-1-tenant/1/pod-jhutar-1-app-tsyqu-comp-0-o4d99e024c3617e7a03cdc59371af8f9a-pod-step-mock-build.log:

+ remote_cmd podman run -v /home/u-04f56220f9bb6a890a064657d38e/results:/results --privileged --rm -ti quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/environment:4b95644a1a230956d9cc8121cc3b15dbd5bdd5d0 mock-hermetic-repo --lockfile /results/buildroot_lock.json --output-repo /results/buildroot_repo
+ ssh -o StrictHostKeyChecking=no u-04f56220f9bb6a890a064657d38e@10.207.4.103 podman run -v /home/u-04f56220f9bb6a890a064657d38e/results:/results --privileged --rm -ti quay.io/redhat-user-workloads/rpm-build-pipeline-tenant/environment:4b95644a1a230956d9cc8121cc3b15dbd5bdd5d0 mock-hermetic-repo --lockfile /results/buildroot_lock.json --output-repo /results/buildroot_repo
time="2025-08-06T06:38:28Z" level=warning msg="The input device is not a TTY. The --tty and --interactive flags might not work properly"
[...]
DEBUG:urllib3.connectionpool:Retry: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/l/libkadm5-1.21.3-7.fc43.aarch64.rpm
DEBUG:urllib3.connectionpool:https://d2lzkl7pfhq30w.cloudfront.net:443 "GET /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/l/libkadm5-1.21.3-7.fc43.aarch64.rpm HTTP/1.1" 504 941
DEBUG:urllib3.util.retry:Incremented Retry for (url='/pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/l/libkadm5-1.21.3-7.fc43.aarch64.rpm'): Retry(total=0, connect=5, read=5, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Retry: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/ansible-srpm-macros-1-18.1.fc43.noarch.rpm
DEBUG:urllib3.connectionpool:Retry: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/alternatives-1.33-2.fc43.aarch64.rpm
DEBUG:urllib3.connectionpool:https://d2lzkl7pfhq30w.cloudfront.net:443 "GET /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/ansible-srpm-macros-1-18.1.fc43.noarch.rpm HTTP/1.1" 504 941
ERROR:__main__:Exception raised for https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/ansible-srpm-macros-1-18.1.fc43.noarch.rpm
urllib3.exceptions.ResponseError: too many 504 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/requests/adapters.py", line 668, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.13/site-packages/urllib3/connectionpool.py", line 932, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='d2lzkl7pfhq30w.cloudfront.net', port=443): Max retries exceeded with url: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/ansible-srpm-macros-1-18.1.fc43.noarch.rpm (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/mock-hermetic-repo", line 62, in download_file
    with request_with_retry().get(url, stream=True, timeout=60) as response:
         ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.13/site-packages/requests/adapters.py", line 692, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='d2lzkl7pfhq30w.cloudfront.net', port=443): Max retries exceeded with url: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/ansible-srpm-macros-1-18.1.fc43.noarch.rpm (Caused by ResponseError('too many 504 error responses'))
DEBUG:urllib3.connectionpool:Retry: /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/b/binutils-2.45-1.fc43.aarch64.rpm
DEBUG:urllib3.connectionpool:https://d2lzkl7pfhq30w.cloudfront.net:443 "GET /pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/alternatives-1.33-2.fc43.aarch64.rpm HTTP/1.1" 504 941
ERROR:__main__:Exception raised for https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/a/alternatives-1.33-2.fc43.aarch64.rpm
urllib3.exceptions.ResponseError: too many 504 error responses
[...]